# Generated by Django 4.1.3 on 2022-11-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rec', models.IntegerField(unique=True)),
                ('name_rec', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ing', models.IntegerField(unique=True)),
                ('name_ing', models.CharField(max_length=200)),
                ('id_rec', models.ManyToManyField(to='recipe.recette')),
            ],
        ),
    ]
