# Generated by Django 4.1.3 on 2022-11-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='id_rec',
        ),
        migrations.AddField(
            model_name='recette',
            name='id_ing',
            field=models.ManyToManyField(to='recipe.ingredient'),
        ),
    ]
