<<<<<<< HEAD
# Generated by Django 4.1.3 on 2022-11-14 12:59
=======
# Generated by Django 4.1.3 on 2022-11-14 13:00
>>>>>>> 7420b4df70c344115076690611ab7c20417be36c

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='id_rec',
        ),
        migrations.AddField(
            model_name='recette',
            name='id_ing',
            field=models.ManyToManyField(to='recipe.ingredient'),
        ),
    ]
